### ISSUE TITLE
Fix static text editor

### ISSUE THREAD

**Issue by huisit** [thepoly/Pipeline#71] opened 2017-04-20 20:22 UTC
After changing component structure, clicking to see details for a story does not change the text in the live editor.

The URL is routed with the correct ID, and all other details/information in the StoryDetail component change, but the text editor shows the text for the first story, unless the URL is entered/refreshed manually.

**Comment by kochman** [comment] 2017-04-22 15:29
I think the problem is that the iframe src attribute is changed whenever a different story is selected, but the real-time editor does not change the active document. It currently only does this on document load.

**Comment by kochman** [comment] 2017-04-22 15:52
Resolved in 42eef0d.

**Closed by kochman** 2017-04-22 15:52 UTC
